In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=2, n_targets=1, noise=0.3)

In [3]:
X

array([[ 0.42525028, -1.13087043],
       [ 0.46717699, -0.17244741],
       [ 0.19854223, -0.00206563],
       ...,
       [ 0.73420333, -0.27214136],
       [-0.47712373, -0.28985181],
       [-1.42201252, -0.42572818]])

In [4]:
y

array([-5.91314564e+01,  4.87079051e+00,  6.02969467e+00, -1.24228396e+02,
       -1.26449987e+02, -5.13945423e-01, -8.20097040e+01, -9.06971471e+00,
       -3.78775611e+01,  7.52847953e+01,  3.78998606e+01, -2.60015313e+01,
        7.83028078e+01, -5.79211444e+01,  1.58277394e+02, -9.33298976e+01,
       -4.21215988e+01, -6.98060480e+01, -2.28249655e+00, -7.71678410e+01,
       -6.55025893e+01, -1.72711910e+01, -4.67342322e+01,  2.77682913e+01,
       -2.14462507e+01, -6.23379081e+01, -8.62609444e+01,  3.99177369e+01,
        9.69580802e+00, -8.76934781e+01, -1.03419890e+01, -5.99883786e+01,
       -1.14723687e+02, -1.45291073e+02, -1.05455473e+01, -8.44004682e+01,
       -4.00552043e+01, -7.50174930e+01,  4.00781563e+01,  4.97916015e+01,
       -8.23619665e+01,  2.24247160e+01, -7.96880453e+01, -3.99635499e+00,
       -1.16431215e+02,  4.93578439e+00, -1.30078432e+02,  1.13353449e+02,
        4.52811785e+01, -8.27968663e+01,  7.56784978e+01, -4.12127826e+01,
       -2.09311024e+00,  

In [5]:
sns.scatterplot(x = pd.DataFrame(X)[0], y=pd.DataFrame(X)[1], hue = y)

<AxesSubplot: xlabel='0', ylabel='1'>

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 1)

In [8]:
X_train

array([[ 1.42613762, -0.75323476],
       [-1.11002489, -0.71465061],
       [-2.11690002, -1.51191385],
       ...,
       [ 0.33837362,  0.44431325],
       [-0.77079341, -0.50655497],
       [-0.01134217, -1.14204919]])

In [9]:
X_test

array([[ 1.92423399e+00,  2.39012522e+00],
       [-5.52427951e-02, -7.54164043e-01],
       [ 2.58298608e-02, -1.25802468e+00],
       [ 7.81182090e-01, -3.29863074e-01],
       [-8.77547171e-01,  9.60355847e-02],
       [ 4.68242753e-02, -1.70923157e+00],
       [ 1.25874084e+00, -4.99294711e-01],
       [ 1.35018100e+00, -1.14671959e+00],
       [-6.88942302e-01,  4.64933943e-04],
       [ 1.05303324e+00, -1.80610071e+00],
       [ 1.37997477e+00, -7.85054891e-01],
       [ 4.47493460e-02, -9.44753414e-01],
       [ 1.39523910e+00, -5.36912585e-01],
       [-1.37701100e+00,  1.18646025e-01],
       [-1.18509157e+00, -1.11116284e-02],
       [-1.07079038e+00, -7.30555816e-01],
       [-4.32639326e-01,  5.72698983e-01],
       [-7.24457961e-01, -8.76327458e-01],
       [ 5.89027602e-01,  2.02890514e+00],
       [-9.23998001e-01,  1.29639426e-01],
       [ 1.18498277e+00, -4.49960963e-01],
       [-9.33962472e-01, -8.61230197e-01],
       [-2.33903926e-01, -3.26214987e-01],
       [-2.

In [10]:
from sklearn.svm import SVR
svr = SVR(kernel = "linear")

In [11]:
svr.fit(X_train, y_train)

SVR(kernel='linear')

In [12]:
y_pred = svr.predict(X_test)

In [13]:
y_pred

array([ 2.20792230e+02, -5.11324347e+01, -8.13263753e+01,  4.68913734e+00,
       -2.32151087e+01, -1.10098851e+02,  9.66462483e+00, -2.95602020e+01,
       -2.31222458e+01, -8.26216099e+01, -4.93127293e+00, -6.02243863e+01,
        1.17929684e+01, -3.85185315e+01, -4.05477822e+01, -8.37096410e+01,
        2.28734801e+01, -8.15972583e+01,  1.52334137e+02, -2.25803516e+01,
        1.04095865e+01, -8.76497034e+01, -2.91765787e+01,  1.01637366e+01,
        2.74974710e+01,  1.17978013e+02,  6.40743889e+00, -3.78052690e+01,
       -4.76380539e+01, -1.12742941e+02, -8.31995804e+01, -3.89973315e+01,
       -3.42315387e+01, -6.53645464e+01,  9.55084349e+01, -2.09647487e+01,
       -1.00130176e+02,  8.48895235e+00, -1.51123441e+02, -5.90091326e+01,
       -6.79106336e+01,  5.26403599e+01, -8.28406332e+01, -3.89663079e+01,
        8.09935526e+01, -7.09750099e+01, -1.01429772e+02,  2.18191857e+01,
       -4.30793255e+01, -6.83669408e+01, -1.32645780e+02, -1.08367917e+01,
        3.47411839e+01, -

In [14]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9999823107998385

In [15]:
from sklearn.model_selection import GridSearchCV
params = {'C': [1, 2, 3, 4, 10, 50, 100],
         'gamma': [0.1, 0.2, 0.001],
         'kernel': ['linear'],
         'epsilon': [0.1, 0.001, 0.2, 0.3]}

In [16]:
params

{'C': [1, 2, 3, 4, 10, 50, 100],
 'gamma': [0.1, 0.2, 0.001],
 'kernel': ['linear'],
 'epsilon': [0.1, 0.001, 0.2, 0.3]}

In [27]:
grid = GridSearchCV(SVR(), param_grid=params, cv = 5, verbose = 4)

In [28]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 84 candidates, totalling 420 fits
[CV 1/5] END C=1, epsilon=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=0.1, kernel=linear;, score=1.000 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=0.2, kernel=linear;, score=1.000 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=0.2, kernel=linear;, score=1.000 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=0.2, kernel=linear;, score=1.000 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=0.2, kernel=linear;, score=1.000 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=0.2, kernel=linear;, score=1.000 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=0.001, kern

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [1, 2, 3, 4, 10, 50, 100],
                         'epsilon': [0.1, 0.001, 0.2, 0.3],
                         'gamma': [0.1, 0.2, 0.001], 'kernel': ['linear']},
             verbose=4)

In [29]:
grid.best_params_

{'C': 50, 'epsilon': 0.001, 'gamma': 0.1, 'kernel': 'linear'}

In [30]:
grid.best_score_

0.9999846923760625