In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [4]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples = 1000, n_features=3,noise = 3, random_state=1)

In [5]:
X

array([[ 1.45167891,  0.3416886 , -0.12517266],
       [-0.7003985 , -0.20339445,  0.24266944],
       [-0.10646012, -2.79099641, -0.45611756],
       ...,
       [-0.56282904, -1.2514994 ,  1.29857162],
       [-1.16896134, -1.8994631 , -2.5399554 ],
       [ 0.88608992,  0.31897183,  0.26486763]])

In [6]:
y

array([ 1.39904571e+02, -5.73895194e+01, -2.96893724e+02,  7.21170194e+01,
        5.04726714e+01,  1.57200504e+02,  2.04260303e+02,  2.45152715e+01,
       -4.40087255e+02, -1.69425107e+02,  5.28891813e+01,  2.07289193e+02,
       -9.37774659e+01,  9.35903925e+01, -2.96302269e+02,  7.53450451e+01,
       -1.47200527e+02,  1.14678762e+02,  1.23527566e+02, -1.40769533e+02,
       -1.78451948e+02,  1.22263134e+02, -1.79314709e+01, -8.10963909e+01,
       -6.99232689e+01, -1.53279905e+02,  1.92297657e+02,  2.07265941e+01,
       -8.11609653e+01, -9.59671992e+01,  1.55804815e+02, -7.75749150e+01,
       -8.48911930e+01,  8.07143772e+01,  2.37712896e+02, -2.38146151e+02,
        2.98373697e+02, -4.62391257e+01,  2.51304584e+02,  1.75129670e+02,
       -1.45707642e+00, -3.00146368e+02, -2.62857003e+02,  1.67565370e+01,
        1.47162845e+02, -5.80689227e+01, -1.22442048e+01,  3.53504499e+02,
       -8.09951545e+01,  3.62727381e+01, -2.03157268e+01,  1.77507056e+02,
        6.75353132e+01,  

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [8]:
X_train.shape, X_test.shape

((700, 3), (300, 3))

In [9]:
from sklearn.neighbors import KNeighborsRegressor
reg = KNeighborsRegressor()

In [10]:
reg

KNeighborsRegressor()

In [13]:
reg.fit(X_train, y_train)

KNeighborsRegressor()

In [14]:
y_pred = reg.predict(X_test)

In [15]:
y_pred

array([-5.45907895e+01, -1.66542112e+01, -1.02670933e+02,  3.25477062e+00,
       -3.49878648e+00,  3.05337027e+00,  2.72307130e+02, -5.31495941e+01,
        1.30269223e+02,  9.05495433e+00, -1.80370128e+02, -3.89863517e+00,
        1.48966226e+02,  7.47651654e+00, -1.55147261e+02,  5.74693089e+01,
       -1.88505115e+02,  1.91841636e+02, -4.20743451e+01,  2.31728313e+01,
        1.52253591e+02,  1.18397495e+02, -1.08016768e+02, -3.78552486e+01,
       -2.84220419e+01,  3.25701699e+02,  1.80547908e+02,  3.12251019e+01,
        1.25594641e+01,  8.07032655e+01, -8.07787801e+01, -9.46545680e+00,
       -6.46579763e+01,  2.74254912e+02, -2.13017718e+01, -1.94262735e+02,
        1.41070702e+02,  2.05684734e+02, -1.23838898e+01,  1.70885971e+02,
        4.09981533e+00,  1.64511777e+02,  3.41050958e+01, -2.16773210e+02,
       -2.20185824e+02, -1.09640760e+01, -2.11455587e+02, -2.64504330e+02,
       -1.13896939e+02,  1.46051502e+02, -2.19776484e+02,  2.33437075e+02,
       -5.05765717e+00, -

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.969184658609626

In [17]:
param_grid = {"n_neighbors": [3, 5, 6, 7, 10, 12, 15],
             'algorithm': ['ball_tree', 'brute', 'kd_tree'],
             'leaf_size': [20, 30, 40 , 50]}

In [18]:
param_grid

{'n_neighbors': [3, 5, 6, 7, 10, 12, 15],
 'algorithm': ['ball_tree', 'brute', 'kd_tree'],
 'leaf_size': [20, 30, 40, 50]}

In [19]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator=reg, param_grid=param_grid, cv = 5, verbose=3)
grid

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['ball_tree', 'brute', 'kd_tree'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 10, 12, 15]},
             verbose=3)

In [20]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 84 candidates, totalling 420 fits
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.968 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.972 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.967 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.979 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=3;, score=0.958 total time=   0.0s
[CV 1/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.972 total time=   0.0s
[CV 2/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.969 total time=   0.0s
[CV 3/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.968 total time=   0.0s
[CV 4/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.972 total time=   0.0s
[CV 5/5] END algorithm=ball_tree, leaf_size=20, n_neighbors=5;, score=0.945 total t

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['ball_tree', 'brute', 'kd_tree'],
                         'leaf_size': [20, 30, 40, 50],
                         'n_neighbors': [3, 5, 6, 7, 10, 12, 15]},
             verbose=3)

In [21]:
grid.best_params_

{'algorithm': 'ball_tree', 'leaf_size': 20, 'n_neighbors': 3}

In [22]:
grid.best_score_

0.9687257312132287