In [1]:

import numpy as np

# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Using np.dot for matrix multiplication
matrix_product = np.dot(A, B)
print("Matrix product using np.dot:\n", matrix_product)

# Using @ operator for matrix multiplication (Python 3.5 and later)
matrix_product = A @ B
print("Matrix product using @ operator:\n", matrix_product)


Matrix product using np.dot:
 [[19 22]
 [43 50]]
Matrix product using @ operator:
 [[19 22]
 [43 50]]


In [2]:
import numpy as np
import time

# Generate two random NumPy arrays with one million elements each
array1 = np.random.rand(1000000)
array2 = np.random.rand(1000000)

# Measure time for the vectorized version using np.dot
start_time_vectorized = time.time()
result_vectorized = np.dot(array1, array2)
end_time_vectorized = time.time()

# Print the time taken for the vectorized version
print("Time taken for vectorized calculation: " + str(1000 * (end_time_vectorized - start_time_vectorized)) + " milliseconds")

# Reset result_vectorized to 0
result_vectorized = 0

# Measure time for the version using a for loop
start_time_for_loop = time.time()
for index in range(1000000):
    result_vectorized += array1[index] * array2[index]
end_time_for_loop = time.time()

# Print the time taken for the for loop version
print("Time taken for calculation using a for loop: " + str(1000 * (end_time_for_loop - start_time_for_loop)) + " milliseconds")


Time taken for vectorized calculation: 13.105154037475586 milliseconds
Time taken for calculation using a for loop: 735.1412773132324 milliseconds


In [28]:
np.array(np.matrix([[1, 2], [5, 6]]))

array([[1, 2],
       [5, 6]])

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [23]:
np.count_nonzero(arr)

6

In [29]:
import numpy as geek 
  
my_scalar = 12
   
print ("Input  scalar : ", my_scalar) 
    
out_arr = geek.asanyarray(my_scalar)  
print ("output array from input scalar : ", out_arr)  
print(type(out_arr)) 

Input  scalar :  12
output array from input scalar :  12
<class 'numpy.ndarray'>
