In [1]:
import numpy as np
data = np.array([[1], [2], [3]])

In [4]:
data.ndim

2

In [5]:
data

array([[1],
       [2],
       [3]])

In [7]:
a=np.squeeze(data)

In [10]:
a

array([1, 2, 3])

In [8]:
a.ndim

1

In [11]:
#repeat
data

array([[1],
       [2],
       [3]])

In [12]:
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [14]:
a = np.array([[1, 2], [3, 4]])

In [15]:
a

array([[1, 2],
       [3, 4]])

In [16]:
np.repeat(a, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [18]:
a

array([[1, 2],
       [3, 4]])

In [17]:
np.repeat(a, 2, axis = 1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [19]:
np.repeat(a, 2, axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [20]:
data

array([[1],
       [2],
       [3]])

In [25]:
np.roll(data, -2)

array([[3],
       [1],
       [2]])

In [24]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [28]:
a = np.array([[[1, 2], [3, 4], [5,6]]])

In [29]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [36]:
np.roll(a, 2, axis = 0)

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [37]:
#binary operation on array

In [39]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [40]:
arr1

array([[2, 7, 1, 6],
       [4, 7, 4, 2],
       [7, 9, 8, 4]])

In [41]:
arr2

array([[3, 9, 6, 7],
       [2, 7, 4, 7],
       [9, 3, 6, 3]])

In [43]:
arr1+arr2

array([[ 5, 16,  7, 13],
       [ 6, 14,  8,  9],
       [16, 12, 14,  7]])

In [44]:
arr1*arr2

array([[ 6, 63,  6, 42],
       [ 8, 49, 16, 14],
       [63, 27, 48, 12]])

In [45]:
arr1 / arr2

array([[0.66666667, 0.77777778, 0.16666667, 0.85714286],
       [2.        , 1.        , 1.        , 0.28571429],
       [0.77777778, 3.        , 1.33333333, 1.33333333]])

In [46]:
arr1 - arr2

array([[-1, -2, -5, -1],
       [ 2,  0,  0, -5],
       [-2,  6,  2,  1]])

In [47]:
arr1 ** arr2

array([[       8, 40353607,        1,   279936],
       [      16,   823543,      256,      128],
       [40353607,      729,   262144,       64]])

In [51]:
arr1

array([[2, 7, 1, 6],
       [4, 7, 4, 2],
       [7, 9, 8, 4]])

In [52]:
arr2

array([[3, 9, 6, 7],
       [2, 7, 4, 7],
       [9, 3, 6, 3]])

In [48]:
arr1 > arr2

array([[False, False, False, False],
       [ True, False, False, False],
       [False,  True,  True,  True]])

In [49]:
~arr1

array([[ -3,  -8,  -2,  -7],
       [ -5,  -8,  -5,  -3],
       [ -8, -10,  -9,  -5]])

In [50]:
arr1

array([[2, 7, 1, 6],
       [4, 7, 4, 2],
       [7, 9, 8, 4]])

In [ ]:
#Numpy string function

In [60]:
arr = np.array(["pw", "skills"])

In [61]:
arr

array(['pw', 'skills'], dtype='<U6')

In [62]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [63]:
np.char.upper(np.array(["Ajay"]))

array(['AJAY'], dtype='<U4')

In [64]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [65]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [66]:
#Mathematical function


arr1

array([[2, 7, 1, 6],
       [4, 7, 4, 2],
       [7, 9, 8, 4]])

In [67]:
np.sin(arr1)

array([[ 0.90929743,  0.6569866 ,  0.84147098, -0.2794155 ],
       [-0.7568025 ,  0.6569866 , -0.7568025 ,  0.90929743],
       [ 0.6569866 ,  0.41211849,  0.98935825, -0.7568025 ]])

In [68]:
np.cos(arr1)

array([[-0.41614684,  0.75390225,  0.54030231,  0.96017029],
       [-0.65364362,  0.75390225, -0.65364362, -0.41614684],
       [ 0.75390225, -0.91113026, -0.14550003, -0.65364362]])

In [69]:
np.tan(arr1)

array([[-2.18503986,  0.87144798,  1.55740772, -0.29100619],
       [ 1.15782128,  0.87144798,  1.15782128, -2.18503986],
       [ 0.87144798, -0.45231566, -6.79971146,  1.15782128]])

In [70]:
np.log10(arr1)

array([[0.30103   , 0.84509804, 0.        , 0.77815125],
       [0.60205999, 0.84509804, 0.60205999, 0.30103   ],
       [0.84509804, 0.95424251, 0.90308999, 0.60205999]])

In [71]:
np.exp(arr1)

array([[7.38905610e+00, 1.09663316e+03, 2.71828183e+00, 4.03428793e+02],
       [5.45981500e+01, 1.09663316e+03, 5.45981500e+01, 7.38905610e+00],
       [1.09663316e+03, 8.10308393e+03, 2.98095799e+03, 5.45981500e+01]])

In [73]:
np.power(arr1, 3)

array([[  8, 343,   1, 216],
       [ 64, 343,  64,   8],
       [343, 729, 512,  64]], dtype=int32)

In [74]:
np.mean(arr1)

5.083333333333333

In [75]:
np.max(arr1)

9

In [76]:
np.std(arr1)

2.4986107250941583

In [77]:
np.var(arr1)

6.243055555555556

In [78]:
np.max(arr1)

9

In [79]:
arr1 - arr2

array([[-1, -2, -5, -1],
       [ 2,  0,  0, -5],
       [-2,  6,  2,  1]])

In [80]:
np.subtract(arr1, arr2)

array([[-1, -2, -5, -1],
       [ 2,  0,  0, -5],
       [-2,  6,  2,  1]])

In [81]:
arr1 * arr2

array([[ 6, 63,  6, 42],
       [ 8, 49, 16, 14],
       [63, 27, 48, 12]])

In [82]:
np.multiply(arr1, arr2)

array([[ 6, 63,  6, 42],
       [ 8, 49, 16, 14],
       [63, 27, 48, 12]])

In [83]:
np.mod(arr1, arr2) #return element wise remainder

array([[2, 7, 1, 6],
       [0, 0, 0, 2],
       [7, 0, 2, 1]])

In [84]:
np.power(arr1, arr2)

array([[       8, 40353607,        1,   279936],
       [      16,   823543,      256,      128],
       [40353607,      729,   262144,       64]])

In [85]:
np.sqrt(arr1)

array([[1.41421356, 2.64575131, 1.        , 2.44948974],
       [2.        , 2.64575131, 2.        , 1.41421356],
       [2.64575131, 3.        , 2.82842712, 2.        ]])

In [ ]:
#sort search

In [86]:
arr = np.array([5, 6, 1, 2])

In [87]:
arr

array([5, 6, 1, 2])

In [88]:
np.sort(arr)

array([1, 2, 5, 6])

In [106]:
arr = np.array([5, 6,100, 200, 1, 2, 8, 9])

In [97]:
# a = np.sort(arr)

In [107]:
arr

array([  5,   6, 100, 200,   1,   2,   8,   9])

In [109]:
np.sort(arr)

array([  1,   2,   5,   6,   8,   9, 100, 200])

In [110]:
np.searchsorted(arr, 3)

6

In [89]:
np.searchsorted(arr, 3)

4

In [90]:
arr1 = np.array([0, 1, 2, 3, 0, 4])
np.count_nonzero(arr1)

4

In [91]:
arr1 > 0

array([False,  True,  True,  True, False,  True])

In [115]:
arr1

array([0, 1, 2, 3, 0, 4])

In [114]:
np.where(arr1 > 0)

(array([1, 2, 3, 5], dtype=int64),)

In [93]:
np.extract(arr1 > 0, arr1)

array([1, 2, 3, 4])

In [112]:
arr1.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

In [ ]:
#matrix >> 2d array

In [116]:
import numpy.matlib as nm

In [117]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [118]:
nm.ones((3, 4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [119]:
#Numpy linear algebra

In [120]:
arr1

array([0, 1, 2, 3, 0, 4])

In [121]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [125]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])

In [126]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [132]:
a  = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [133]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [134]:
b = np.array([16, -8, 0])

In [135]:
b

array([16, -8,  0])

In [136]:
np.linalg.solve(a, b)

array([0.90162081, 2.89483603, 1.88465888])

In [137]:
arr1

array([[2, 3],
       [4, 5]])

In [138]:
5*2 - 3*4

-2

In [139]:
np.linalg.det(arr1)

-2.0

In [140]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])