1. What is a Python library? Why do we use Python libraries?

solution =>

A Python library is a collection of related modules12. It contains bundles of code that can be used repeatedly in different programs1. Each module in a library is a file containing Python definitions and statements3. The library makes Python programming simpler and more convenient for the programmer, as they don’t need to write the same code again and again for different programs1.

We use Python libraries for several reasons:

Code Reusability: Libraries contain precompiled codes that can be used later on in a program for some specific well-defined operations1. This increases code reusability as the same code can be used in various relevant projects and operations2.

Efficiency: Libraries provide pre-written and optimized code, which can make your programs more efficient and faster1.

Simplicity: Libraries often have functions that simplify complex coding tasks, making it easier for programmers to implement functionality without having to worry about the details1.

2. What is the difference between Numpy array and List?

solution =>

The main differences between a Numpy array and a Python list:

1. Data Type:
Numpy Array: It is a homogeneous array, which means all elements in the array must be of the same data type12.

Python List: It can be heterogeneous, meaning it can hold different data types1.

2. Memory Usage and Performance:
Numpy Array: It stores elements of the same data type, making them more compact and memory-efficient than lists1. It also facilitates advanced mathematical and other types of operations on large numbers of data1. These operations are executed more efficiently and with less code than is possible using Python’s built-in sequences1.

Python List: Lists in Python store additional information about each element, such as its type and reference count1. This overhead can be significant when dealing with a large number of elements1. Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency1.

3. Operations:
Numpy Array: Element-wise operation is possible1. It has various functions, methods, and variables, to ease our task of matrix computation1.
Python List: Element-wise operation is not possible on the list1.

4.Dimension:
Numpy Array: We can create an N-dimensional array in Python using Numpy1.
Python List: Python list is by default 1-dimensional. But we can create an N-Dimensional list1.

5. Size:
Numpy Array: You can’t change the size of a numpy array without making a full copy34.
Python List: You can append elements to a list34.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [6]:
import numpy as np

# Your array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Find shape
shape = array.shape

# Find size
size = array.size

# Find dimension
dimension = array.ndim

print(f"Shape: {shape}, Size: {size}, Dimension: {dimension}")


Shape: (3, 4), Size: 12, Dimension: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [7]:
import numpy as np

# Your array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Access first row
first_row = array[0]

print(first_row)


[1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
import numpy as np

# Your array
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Extract odd-indexed elements
odd_indexed_elements = array[::2, 1::2]

print(odd_indexed_elements)


[[ 2  4]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [11]:
# we can generate a random 3x3 matrix with values between 0 and 1 using the numpy.random.rand function

import numpy as np

# Generate a random 3x3 matrix with values between 0 and 1
matrix = np.random.rand(3, 3)

print(matrix)


[[0.06763995 0.96535763 0.7175871 ]
 [0.31729045 0.97576733 0.32481441]
 [0.84803441 0.78658359 0.6780126 ]]


8. Describe the difference between np.random.rand and np.random.randn?

solution => 

The differences between numpy.random.rand and numpy.random.randn:

numpy.random.rand: This function generates random numbers from a uniform distribution in the range [0, 1)12. In a uniform distribution, all values within the given interval are equally likely to be drawn2.

numpy.random.randn: This function generates random numbers from a normal (Gaussian) distribution with a mean of 0 and a variance of 112. In a normal distribution, values are more likely to be closer to the mean, with the likelihood decreasing as you move away from the mean2.

9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [5]:
import numpy as np

# Your original 2D array
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

# Increase dimension
array_3d = array_2d[:, :, np.newaxis]

print(array_3d)


[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [4]:
# You can use the numpy.transpose function or the T attribute of a NumPy array to transpose a matrix. Here’s how you can do it:

import numpy as np

# Define the matrix
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Transpose the matrix
transposed_matrix = matrix.T

print(transposed_matrix)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A

In [3]:
import numpy as np

# Define the matrices
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Element-wise multiplication
elementwise_product = np.multiply(A2, B2)

# Matrix multiplication
matrix_product = np.matmul(A2, B2.T)  # We transpose B2 because A2 and B2 are not compatible for multiplication as they are

# Addition
sum_of_matrices = np.add(A2, B2)

# Subtraction of B2 from A2
difference = np.subtract(A2, B2)

# Division of B2 by A2
division = np.divide(B2, A2)

print("Element-wise multiplication:\n", elementwise_product)
print("Matrix multiplication:\n", matrix_product)
print("Addition of both matrices:\n", sum_of_matrices)
print("Subtraction of B2 from A2:\n", difference)
print("Division of B2 by A2:\n", division)


Element-wise multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition of both matrices:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction of B2 from A2:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division of B2 by A2:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

solution =>

The function numpy.ndarray.byteswap is used to swap the byte order of an array.

13. What is the significance of the np.linalg.inv function?

solution => 

The np.linalg.inv function in NumPy is used to compute the (multiplicative) inverse of a matrix.

Given a square matrix A, the inverse A^-1 is such that when A is multiplied by A^-1, the result is the identity matrix I. In other words, A * A^-1 = A^-1 * A = I.

Here’s an example of how to use np.linalg.inv:

import numpy as np

Define a square matrix

A = np.array([[1, 2], [3, 4]])

Compute its inverse

A_inv = np.linalg.inv(A)

print("A:\n", A)

print("Inverse of A:\n", A_inv)

14. What does the np.reshape function do, and how is it used?

solution =>

The np.reshape function in NumPy is used to give a new shape to an array without changing its data. Here is the basic usage:



import numpy as np

Create a 1D array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

Reshape it to a 2D array with 2 rows and 4 columns

reshaped_arr = np.reshape(arr, (2, 4))

print(reshaped_arr)

This will output:

[[1 2 3 4]
 [5 6 7 8]]

In this example, we reshaped a 1D array with 8 elements into a 2D array with 2 rows and 4 columns.

15. What is broadcasting in Numpy?

solution => 

Broadcasting in NumPy is a powerful feature that allows arrays of different shapes to be used in arithmetic operations. It does this by automatically expanding the dimensions of the smaller array to match the larger one, without making copies of the data.

Here’s a simple example:


import numpy as np

a = np.array([1, 2, 3])

b = 2

print(a * b)  # Outputs: array([2, 4, 6])